using System;
using System.Linq;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using CloudSentinel.Model;

namespace CloudSentinel.Report
{
    public class PdfReportGenerator
    {
        private static readonly string ColorBlue      = "#1F4E79";
        private static readonly string ColorMidBlue   = "#2E75B6";
        private static readonly string ColorLightBlue = "#D6E4F0";
        private static readonly string ColorCritical  = "#C00000";
        private static readonly string ColorHigh      = "#C55A11";
        private static readonly string ColorMedium    = "#7F6000";
        private static readonly string ColorLow       = "#375623";
        private static readonly string ColorGray      = "#F5F5F5";
        private static readonly string ColorDarkGray  = "#444444";

        public void Generate(ScanResult result, string outputPath)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(40);
                    page.DefaultTextStyle(t => t.FontFamily("Arial").FontSize(10).FontColor(ColorDarkGray));

                    // ── HEADER ──────────────────────────────────────────────
                    page.Header().Column(col =>
                    {
                        col.Item().BorderBottom(2).BorderColor(ColorMidBlue).PaddingBottom(8).Row(row =>
                        {
                            row.RelativeItem().Column(c =>
                            {
                                c.Item().Text("CloudSentinel")
                                    .FontSize(22).Bold().FontColor(ColorBlue);
                                c.Item().Text("Security Misconfiguration Report")
                                    .FontSize(11).FontColor(ColorMidBlue);
                            });
                            row.ConstantItem(120).AlignRight().AlignMiddle().Column(c =>
                            {
                                c.Item().Text($"Score: {result.RiskScore} / 100")
                                    .FontSize(13).Bold().FontColor(GradeColor(result.Grade));
                                c.Item().Text($"Grade: {result.Grade}")
                                    .FontSize(13).Bold().FontColor(GradeColor(result.Grade));
                            });
                        });
                        col.Item().PaddingBottom(8);
                    });

                    // ── FOOTER ──────────────────────────────────────────────
                    page.Footer().BorderTop(1).BorderColor(ColorLightBlue).PaddingTop(6).Row(row =>
                    {
                        row.RelativeItem().Text("Generated by CloudSentinel")
                            .FontSize(8).FontColor("#888888");
                        row.RelativeItem().AlignRight()
                            .Text(t =>
                            {
                                t.Span("Page ").FontSize(8).FontColor("#888888");
                                t.CurrentPageNumber().FontSize(8).FontColor("#888888");
                                t.Span(" of ").FontSize(8).FontColor("#888888");
                                t.TotalPages().FontSize(8).FontColor("#888888");
                            });
                    });

                    // ── CONTENT ─────────────────────────────────────────────
                    page.Content().Column(content =>
                    {
                        // ── Executive Summary ────────────────────────────────
                        content.Item().Background(ColorGray).Padding(16).Column(summary =>
                        {
                            summary.Item().Text("Executive Summary")
                                .FontSize(14).Bold().FontColor(ColorBlue);
                            summary.Item().PaddingTop(8).Table(t =>
                            {
                                t.ColumnsDefinition(c =>
                                {
                                    c.RelativeColumn();
                                    c.RelativeColumn();
                                    c.RelativeColumn();
                                    c.RelativeColumn();
                                    c.RelativeColumn();
                                });

                                void SummaryCell(string label, string value, string color)
                                {
                                    t.Cell().Background("FFFFFF").Padding(8).Column(c =>
                                    {
                                        c.Item().Text(label).FontSize(8).FontColor("#888888");
                                        c.Item().Text(value).FontSize(16).Bold().FontColor(color);
                                    });
                                }

                                SummaryCell("RISK SCORE",     result.RiskScore.ToString(), GradeColor(result.Grade));
                                SummaryCell("GRADE",          result.Grade,                GradeColor(result.Grade));
                                SummaryCell("TOTAL FINDINGS", result.TotalFindings.ToString(), ColorDarkGray);
                                SummaryCell("CRITICAL / HIGH",
                                    $"{result.Critical.Count()} / {result.High.Count()}", ColorCritical);
                                SummaryCell("MEDIUM / LOW",
                                    $"{result.Medium.Count()} / {result.Low.Count()}", ColorMedium);
                            });
                        });

                        content.Item().PaddingVertical(12);

                        // ── Findings by Severity ─────────────────────────────
                        content.Item().Text("Findings").FontSize(14).Bold().FontColor(ColorBlue);
                        content.Item().PaddingBottom(6);

                        if (result.TotalFindings == 0)
                        {
                            content.Item().Background("#F0FDF4").Padding(12)
                                .Text("No misconfigurations detected. Configuration is clean.")
                                .FontColor(ColorLow);
                        }
                        else
                        {
                            // Findings table
                            content.Item().Table(table =>
                            {
                                table.ColumnsDefinition(cols =>
                                {
                                    cols.ConstantColumn(60);   // Severity
                                    cols.ConstantColumn(55);   // Rule ID
                                    cols.RelativeColumn(2);    // Resource
                                    cols.RelativeColumn(3);    // Description
                                });

                                // Header
                                void HeaderCell(string text) =>
                                    table.Cell()
                                        .Background(ColorMidBlue).Padding(6)
                                        .Text(text).FontSize(9).Bold().FontColor("#FFFFFF");

                                HeaderCell("Severity");
                                HeaderCell("Rule");
                                HeaderCell("Resource");
                                HeaderCell("Description");

                                // Rows — ordered Critical first
                                var ordered = result.Findings
                                    .OrderByDescending(f => f.Severity)
                                    .ToList();

                                bool alternate = false;
                                foreach (var finding in ordered)
                                {
                                    string rowBg = alternate ? "#F9FAFB" : "#FFFFFF";
                                    alternate = !alternate;

                                    void DataCell(string text, bool bold = false)
                                    {
                                        var cell = table.Cell()
                                            .Background(rowBg)
                                            .BorderBottom(1).BorderColor("#E5E7EB")
                                            .Padding(5)
                                            .Text(text)
                                            .FontSize(9);
                                        
                                        if (bold)
                                            cell.Bold();
                                    }

                                    // Severity cell — coloured text
                                    table.Cell()
                                        .Background(rowBg)
                                        .BorderBottom(1).BorderColor("#E5E7EB")
                                        .Padding(5)
                                        .Text(finding.Severity.ToString())
                                        .FontSize(9).Bold()
                                        .FontColor(SeverityColor(finding.Severity));

                                    DataCell(finding.RuleId, bold: true);
                                    DataCell(finding.ResourceName);
                                    DataCell(finding.Description);
                                }
                            });
                        }

                        content.Item().PaddingVertical(14);

                        // ── Remediation Steps ────────────────────────────────
                        content.Item().Text("Remediation Steps").FontSize(14).Bold().FontColor(ColorBlue);
                        content.Item().PaddingBottom(6);

                        if (result.TotalFindings == 0)
                        {
                            content.Item().Text("No remediation required.").FontColor("#888888");
                        }
                        else
                        {
                            var ordered = result.Findings
                                .OrderByDescending(f => f.Severity)
                                .ToList();

                            foreach (var finding in ordered)
                            {
                                content.Item()
                                    .BorderLeft(3).BorderColor(SeverityColor(finding.Severity))
                                    .PaddingLeft(10).PaddingVertical(6)
                                    .Column(c =>
                                    {
                                        c.Item().Row(r =>
                                        {
                                            r.AutoItem()
                                                .Text($"[{finding.Severity}] ")
                                                .FontSize(9).Bold()
                                                .FontColor(SeverityColor(finding.Severity));
                                            r.RelativeItem()
                                                .Text(finding.ResourceName)
                                                .FontSize(9).Bold().FontColor(ColorBlue);
                                        });
                                        c.Item().PaddingTop(3)
                                            .Text(finding.Remediation)
                                            .FontSize(9).FontColor(ColorDarkGray);
                                    });

                                content.Item().PaddingBottom(8);
                            }
                        }

                        // ── Score Explanation ────────────────────────────────
                        content.Item().PaddingVertical(10);
                        content.Item().Background(ColorGray).Padding(12).Column(c =>
                        {
                            c.Item().Text("Score Methodology")
                                .FontSize(11).Bold().FontColor(ColorBlue);
                            c.Item().PaddingTop(6).Table(t =>
                            {
                                t.ColumnsDefinition(cols =>
                                {
                                    cols.RelativeColumn();
                                    cols.RelativeColumn();
                                    cols.RelativeColumn();
                                    cols.RelativeColumn();
                                });

                                void ScoreCell(string severity, string weight, string range, string grade, string color)
                                {
                                    t.Cell().Padding(4).Column(col =>
                                    {
                                        col.Item().Text(severity).FontSize(8).Bold().FontColor(color);
                                        col.Item().Text($"Weight: {weight}").FontSize(8);
                                        col.Item().Text($"Grade {grade}: {range}").FontSize(8).FontColor("#888888");
                                    });
                                }

                                ScoreCell("Critical", "10 pts each", "0–20",  "A", ColorCritical);
                                ScoreCell("High",     "7 pts each",  "21–40", "B", ColorHigh);
                                ScoreCell("Medium",   "4 pts each",  "41–60", "C", ColorMedium);
                                ScoreCell("Low",      "1 pt each",   "61–80", "D", ColorLow);
                            });
                        });
                    });
                });
            })
            .GeneratePdf(outputPath);
        }

        private static string GradeColor(string grade) => grade switch
        {
            "A" => "#15803D",
            "B" => "#166534",
            "C" => "#7F6000",
            "D" => "#C55A11",
            "F" => "#C00000",
            _   => "#444444"
        };

        private static string SeverityColor(Severity severity) => severity switch
        {
            Severity.Critical => "#C00000",
            Severity.High     => "#C55A11",
            Severity.Medium   => "#7F6000",
            Severity.Low      => "#375623",
            _                 => "#444444"
        };
    }
}